name: Deploy Galeria Intercambio (Docker Swarm)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/galeria-intercambio:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/galeria-intercambio:latest

      - name: Deploy direto no servidor
        run: |
          docker pull ${{ secrets.DOCKER_USER }}/galeria-intercambio:latest
          cd ~/stacks/05-apps
          docker stack deploy -c galerias.yml galerias